### ISSUE TITLE
程序中TPi与TPe不同之处是？

### ISSUE THREAD

**Issue by dongdongdong531** [Nicola115/waste-water-treatment-plant#1]
请问，您的程序中'TPi'与'TPe'是不同的变量还是相同变量不同量纲？

**Comment by AveryQi115** [comment]
您好，程序中所有i和e后缀分别代表输入和输出，一组输入和输出是同一量纲的变量；不同的元素可能采用不同的量纲，取决于环境科学那边提供的数据。

**Comment by dongdongdong531** [comment]
> 您好，程序中所有i和e后缀分别代表输入和输出，一组输入和输出是相同量纲的变量；不同的元素可能采用不同的量纲，从而环境科学那边提供的数据。

理解了，感谢您的回复

**Comment by AveryQi115** [comment]
没事，感谢关注，这份代码其实写的挺简陋的hhh
